port: 4000
permalink: /:categories/:year/:month/:title/
base_url: https://christiandinger.com

# Used in feed.xml
name: christiandinger.com
description: christiandinger.com
url: https://christiandinger.com
